---
apiVersion: v1
kind: Pod
metadata:
  name: dolphin-example-mongo-db
  namespace: dolphin-example
  labels:
    app: dolphin-example-mongo-db
spec:
  containers:
  - name: dolphin-example-mongo-db
    image: mongo
    command:
    - "mongod"
    - "--bind_ip"
    - "0.0.0.0"
    - "--port"
    - "27017"
    ports:
    - containerPort: 27017
      name: mongocontainer
---
apiVersion: v1
kind: Service
metadata:
  name: dolphin-example-mongo-db-svc
  namespace: threat-gen
spec:
  selector:
    app: dolphin-example-mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017