---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: dolphin
  labels:
    app: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo
    ports:
    - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: dolphin
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 32162