---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: dolphin
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: dolphin
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 32161